'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=s=>String(s).toLocaleLowerCase('sv').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const STOP=new Set('och i att det som en pa ar av for med till den har de inte om ett vid kan eller sa ska fran man men efter sig vara alla nar dar samt aven dessa detta denna hos under over mot ut in upp ner per'.split(' '));
const colors={lung:'#178b9a',akut:'#b6532f',luft:'#178b9a',inf:'#c28012',neuro:'#7963b6',buk:'#4d8772',vatska:'#2289b6',met:'#a35c91',trauma:'#cc7850',smarta:'#96679b',hjarta:'#b55669',tox:'#738643',neo:'#388782',trygg:'#6181b4'};
const labels={uppsala:'Lokalt PM · Akademiska',karolinska:'Externt PM · Karolinska',nationellt:'Nationellt & övrigt'};
let popularity;let data,source='all',area='all',onlySaved=false,saved=new Set();
try{const v=JSON.parse(localStorage.getItem('ak.barn.saved')||'[]');if(Array.isArray(v))saved=new Set(v.filter(x=>typeof x==='string'));}catch{}
function termsOf(query){return normal(query).split(' ').filter(t=>t.length>1&&!STOP.has(t));}
function hit(hay,t){if(hay.includes(t))return true;if(t.length>=6&&hay.includes(t.slice(0,-2)))return true;if(t.length>=7&&hay.includes(t.slice(0,-3)))return true;return false;}
function matches(d,query){const terms=termsOf(query);if(!terms.length)return true;const hay=normal([d.title,d.publisher,data.areas[d.area],d.scope,...(d.keywords||[])].join(' '));return terms.every(t=>hit(hay,t));}
function reset(){source='all';area='all';onlySaved=false;$('q').value='';render();}
function applyQuery(query){source='all';area='all';onlySaved=false;$('q').value=query;render();$('q').focus();}
function render(){
 $('popularity-status').textContent=popularity.status();
 const q=$('q').value.trim();const stopOnly=!!q&&!termsOf(q).length;
 const base=stopOnly?[]:data.docs.filter(d=>(source==='all'||d.source===source)&&(!onlySaved||saved.has(d.id))&&matches(d,q));
 const shown=base.filter(d=>area==='all'||d.area===area).sort(popularity.compare);
 $('total').textContent=data.docs.length;$('saved-count').textContent=data.docs.filter(d=>saved.has(d.id)).length;
 $('areas').innerHTML=[['all','Alla områden'],...Object.entries(data.areas)].map(([id,t])=>{const n=id==='all'?base.length:base.filter(d=>d.area===id).length;return `<button class="area ${area===id?'active':''}" data-area="${id}" aria-pressed="${area===id}" style="--accent:${colors[id]||'#163c53'}"><span class="area-dot" aria-hidden="true"></span><span>${esc(t)}</span><span class="n">${n}</span></button>`;}).join('');
 document.querySelectorAll('[data-source]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',source===b.dataset.source);});
 $('saved').setAttribute('aria-pressed',onlySaved);$('context').textContent=onlySaved?'DINA SPARADE':q?'SÖKRESULTAT':area==='all'?'HELA BIBLIOTEKET':'KLINISKT OMRÅDE';
 $('results-heading').textContent=area==='all'?(q?'Sök i biblioteket':'PM & riktlinjer'):data.areas[area];
 $('count').textContent=`${shown.length} dokument${q?' för ”'+q+'”':''} · ${source==='all'?'alla källor':source==='uppsala'?'Akademiska':source==='karolinska'?'Karolinska':'nationellt & övrigt'}`;
 $('results').innerHTML=shown.length?shown.map(d=>{const old=d.date&&Number(d.date.slice(0,4))<=2021;const format=d.format||'';return `<article class="card" data-source="${d.source}" style="--accent:${colors[d.area]||colors.akut}"><div class="card-top">${popularity.badge(d)}<span class="source-badge">${labels[d.source]||'Källa'}</span><button class="save" data-save="${esc(d.id)}" aria-pressed="${saved.has(d.id)}" aria-label="${saved.has(d.id)?'Ta bort sparad':'Spara'}: ${esc(d.title)}">${saved.has(d.id)?'★':'☆'}</button></div><h3><a data-count-open="${esc(d.id)}" href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">${esc(d.title)}</a></h3><p class="publisher">${esc(d.publisher)}</p>${d.scope?`<p class="scope">${esc(d.scope)}</p>`:''}<div class="card-meta">${d.date?`<span>Dokumentdatum ${esc(d.date)}</span>`:'<span>Datum: se original</span>'}${d.checked?`<span>Länk ${esc(d.checked)}</span>`:''}${old?'<span class="old">Äldre dokument · kontrollera giltighet</span>':''}${d.archive?'<span class="old">Bibliotekskopia · giltighet ej verifierad</span>':''}</div><div class="card-bottom"><span class="topic">${esc(data.areas[d.area]||d.area)}</span><a data-count-open="${esc(d.id)}" href="${esc(d.url)}" target="_blank" rel="noopener noreferrer" aria-label="Öppna ${esc(d.title)} i ny flik">${format==='Dokumentsamling'?'Öppna samlingen':d.archive?'Sparad PDF':format.includes('PDF')?'Öppna PDF':format.includes('Dokument')?'Öppna dokument':'Till riktlinjen'} ↗</a></div></article>`;}).join(''):`<div class="empty"><h3>${stopOnly?'Inga sökbara ord':onlySaved?'Inga sparade dokument i detta urval':'Inga träffar'}</h3><p>${stopOnly?'Småord som “och”, “vid” och “för” ignoreras. Prova ett mer specifikt ord.':onlySaved?'Spara ett dokument med stjärnan på kortet.':'Prova ett annat sökord, eller ta bort käll- och områdesfilter.'}</p><button id="empty-reset">Visa hela biblioteket</button></div>`;
 document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{area=b.dataset.area;render();const f=document.querySelector(`[data-area="${CSS.escape(area)}"]`);if(f)f.focus();});
 document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('ak.barn.saved',JSON.stringify([...saved]));}catch{}render();const target=document.querySelector(`[data-save="${CSS.escape(id)}"]`);if(target)target.focus();else $('saved').focus();});
 if($('empty-reset'))$('empty-reset').onclick=reset;
}
(async()=>{try{const r=await fetch('./data.json?v=ak-v10s4f');if(!r.ok)throw new Error('data');data=await r.json();if(!Array.isArray(data.docs))throw new Error('format');{const ids=new Set(data.docs.map(d=>d.id));const keep=[...saved].filter(id=>ids.has(id));if(keep.length!==saved.size){saved=new Set(keep);try{localStorage.setItem('ak.barn.saved',JSON.stringify(keep));}catch{}}}popularity=AkPopularity.create('barn',data.docs,render);$('q').oninput=render;$('reset').onclick=reset;$('saved').onclick=()=>{onlySaved=!onlySaved;render();};document.querySelectorAll('button[data-source]').forEach(b=>b.onclick=()=>{source=b.dataset.source;render();});document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>applyQuery(b.dataset.query));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('q').focus();}if(e.key==='Escape'&&document.activeElement===$('q')){$('q').value='';render();}});render();popularity.load();const countOpen=e=>{if(e.type==='auxclick'&&e.button!==1)return;const link=e.target.closest('a[data-count-open]');if(link)popularity.record(link.dataset.countOpen);};document.addEventListener('click',countOpen);document.addEventListener('auxclick',countOpen);}catch(e){$('count').textContent='Biblioteket kunde inte hämtas';$('results').innerHTML='<div class="empty"><h3>Kunde inte ladda riktlinjerna</h3><p>Kontrollera anslutningen och försök igen.</p><button id="retry">Försök igen</button></div>';$('retry').onclick=()=>location.reload();}})();
if('serviceWorker' in navigator)navigator.serviceWorker.register('../sw.js').catch(()=>{});
